### ISSUE TITLE
ToDo Milestone 4

### ISSUE THREAD

**Issue by Zhang-Haipeng** [UBC-MDS/DSCI_522_group408#47]
- [x] Respond to feedbacks  - no orca . - Roc
- [x] Dockerfile  - Jarvis
  - [x] Make docker image
  - [x] Use Docker Hub Automated Build 
- [x] Makefile dependency   - Jack
- [x] Update README
